### ISSUE TITLE
Reproducible server configuration

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/sadserver#18]
Setup a basic linux server using the configuration management tool Ansible. 
- ubuntu common tasks
  - [x] automatic security updates
  - [x] firewall
  - [x] ssh
    - [x] fail2ban
  - [ ] configuration of users (#23)
    - [x] adding keys
  - [ ] filesystem permissions (#20)
- LEMP stack
  - [x] nginx
    - [ ] site template (#24)
    - [ ] let's encrypt (#16)
  - [ ] mariadb (#25)
  - [ ] php-fpm (#26, think of #19)
- python
  - [ ] python environment (#27)
  - [ ] studystatus (#28)
- koala
  - [ ] rails (#29)
  - [ ] install koala codebase (#30)
  - [ ] other koala dependencies (#31)
- [ ] setup email (#32)
- [ ] logging/monitoring (#33)
- [ ] vault (#17)
- ansible-specific tasks
  - [x] deploying as non-root user (#34)

(List edited by @tomwassenberg)
